# Welcome: Your First CDM

**Connect to an OMOP CDM and inspect tables and row counts.**

## You will learn
- What the CDM reference object (`cdm`) is and how it holds OMOP tables
- How to list CDM tables and access them by name
- How to get person count and preview a few rows
- How to get a quick snapshot of your CDM
- How to subset a cdm reference object to one or more `person_id`s
- How to clean up the connection when done

---

## Motivating question

*"How many people are in this database, and what do the first few person rows look like?"*

---

## Setup

We will use the **GiBleed** Eunomia example dataset and connect via DuckDB.

In [58]:
import cdmconnector as cc
import ibis as ib

print(cc.example_datasets())

path = cc.eunomia_dir("synpuf-1k", cdm_version="5.3")
con = ib.duckdb.connect(path)
cdm = cc.cdm_from_con(con, cdm_schema="main", write_schema="main")
print(cdm)

('GiBleed', 'synthea-allergies-10k', 'synthea-anemia-10k', 'synthea-breast_cancer-10k', 'synthea-contraceptives-10k', 'synthea-covid19-10k', 'synthea-covid19-200k', 'synthea-dermatitis-10k', 'synthea-heart-10k', 'synthea-hiv-10k', 'synthea-lung_cancer-10k', 'synthea-medications-10k', 'synthea-metabolic_syndrome-10k', 'synthea-opioid_addiction-10k', 'synthea-rheumatoid_arthritis-10k', 'synthea-snf-10k', 'synthea-surgery-10k', 'synthea-total_joint_replacement-10k', 'synthea-veteran_prostate_cancer-10k', 'synthea-veterans-10k', 'synthea-weight_loss-10k', 'synpuf-1k', 'synpuf-110k', 'empty_cdm', 'Synthea27NjParquet')
eunomia_dir: data folder = /Users/ablack/eunomia_data_py
('GiBleed', 'synthea-allergies-10k', 'synthea-anemia-10k', 'synthea-breast_cancer-10k', 'synthea-contraceptives-10k', 'synthea-covid19-10k', 'synthea-covid19-200k', 'synthea-dermatitis-10k', 'synthea-heart-10k', 'synthea-hiv-10k', 'synthea-lung_cancer-10k', 'synthea-medications-10k', 'synthea-metabolic_syndrome-10k', 'synthea-opioid_addiction-10k', 'synthea-rheumatoid_arthritis-10k', 'synthea-snf-10k', 'synthea-surgery-10k', 'synthea-total_joint_replacement-10k', 'synthea-veteran_prostate_cancer-10k', 'synthea-veterans-10k', 'synthea-weight_loss-10k', 'synpuf-1k', 'synpuf-110k', 'empty_cdm', 'Synthea27NjParquet')
eunomia_dir: data folder = /Users/ablack/eunomia_data_py

# OMOP CDM reference (duckdb) of Synpuf

  omop tables: care_site, cdm_source, concept, concept_ancestor, concept_relationship, concept_synonym, condition_era, condition_occurrence, cost, death, device_exposure, dose_era, drug_era, drug_exposure, drug_strength, fact_relationship, location, measurement, note, note_nlp, observation, observation_period, payer_plan_period, person, procedure_occurrence, provider, specimen, visit_detail, visit_occurrence, vocabulary
  cohort tables: -
  achilles tables: -
  other tables: -
# OMOP CDM reference (duckdb) of Synpuf

  omop tables: care_site, cdm_source, concept, concept_ancestor, concept_relationship, concept_synonym, condition_era, condition_occurrence, cost, death, device_exposure, dose_era, drug_era, drug_exposure, drug_strength, fact_relationship, location, measurement, note, note_nlp, observation, observation_period, payer_plan_period, person, procedure_occurrence, provider, specimen, visit_detail, visit_occurrence, vocabulary
  cohort tables: -
  achilles tables: -
  other tables: -

## Explore: CDM reference and table listing

The `cdm` object holds a mapping of table names to Ibis table expressions. List available tables.

In [59]:
# List CDM table names
cdm.tables

['care_site',
 'cdm_source',
 'concept',
 'concept_ancestor',
 'concept_relationship',
 'concept_synonym',
 'condition_era',
 'condition_occurrence',
 'cost',
 'death',
 'device_exposure',
 'dose_era',
 'drug_era',
 'drug_exposure',
 'drug_strength',
 'fact_relationship',
 'location',
 'measurement',
 'note',
 'note_nlp',
 'observation',
 'observation_period',
 'payer_plan_period',
 'person',
 'procedure_occurrence',
 'provider',
 'specimen',
 'visit_detail',
 'visit_occurrence',
 'vocabulary']

In [60]:
cdm.person.schema()

ibis.Schema {
  person_id                    int32
  gender_concept_id            int32
  year_of_birth                int32
  month_of_birth               int32
  day_of_birth                 int32
  birth_datetime               timestamp(6)
  race_concept_id              int32
  ethnicity_concept_id         int32
  location_id                  int32
  provider_id                  int32
  care_site_id                 int32
  person_source_value          string
  gender_source_value          string
  gender_source_concept_id     int32
  race_source_value            string
  race_source_concept_id       int32
  ethnicity_source_value       string
  ethnicity_source_concept_id  int32
}

## Person count

Use `count` and `execute` to execute an expression and get a pandas DataFrame. For a scalar (e.g. count), the result is a small DataFrame.

In [61]:
cdm.person.count().execute()

1000

In [62]:
# Preview a few rows (limit to avoid large output)
cdm.person.head(10).execute()

   person_id  gender_concept_id  ...  ethnicity_source_value  ethnicity_source_concept_id
0          0               8507  ...  Not Hispanic or Latino                            0
1          1               8532  ...                  Others                            0
2          2               8532  ...  Not Hispanic or Latino                            0
3          3               8507  ...  Not Hispanic or Latino                            0
4          4               8507  ...  Not Hispanic or Latino                            0
5          5               8532  ...  Not Hispanic or Latino                            0
6          6               8532  ...  Not Hispanic or Latino                            0
7          7               8507  ...  Not Hispanic or Latino                            0
8          8               8532  ...  Not Hispanic or Latino                            0
9          9               8532  ...  Not Hispanic or Latino                            0

[10 rows x 18 columns]

Behind the scenes Ibis sends a SQL query to our database

In [63]:
cdm.person.head(5).compile()

'SELECT * FROM "main"."person" AS "t0" LIMIT 5'

The cdm reference stores the cdm name and cdm version which are often helpful. The cdm name is set by looking it up in the `cdm_source` table of the OMOP CDM database. However it can be overridden by the `cdm_name` argument in `cdm_from_con`.

In [64]:
print("cdm.name:", cdm.name)
print("cdm.version:", cdm.version)

cdm.name: Synpuf
cdm.version: 5.3
cdm.name: Synpuf
cdm.version: 5.3

CDMConnector has a snapshot function that will return a dataframe with some summary information about the database. It's a quick way to get some helpful metadata.

In [65]:
cdm.snapshot()

  cdm_name cdm_source_name cdm_description  ... latest_observation_period_end_date snapshot_date cdm_data_hash
0   Synpuf          Synpuf                  ...                2010-12-31 00:00:00    2026-02-01

[1 rows x 14 columns]

Flattening is a CDM transformation that puts all of the CDM's clinical data into a single table. It can be helpful for getting a *timeline* view of a person's medical history.

In [66]:
cdm.flatten().execute().sort_values(by=["person_id", "start_date"])

        person_id  ...                                  type_concept_name
58521           0  ...                Carrier claim header - 1st position
92392           0  ...                Carrier claim detail - 1st position
209028          0  ...                Carrier claim detail - 1st position
77318           0  ...                Carrier claim detail - 2nd position
119492          0  ...  Physician administered drug (identified as pro...
...           ...  ...                                                ...
189748       1494  ...                Carrier claim detail - 1st position
34969        1494  ...                Carrier claim detail - 1st position
102005       1494  ...                Carrier claim header - 2nd position
153212       1494  ...                Carrier claim detail - 1st position
237358       1494  ...                Carrier claim header - 3rd position

[271901 rows x 10 columns]

 Often CDMs are too big to bring into python so normally we would filter the cdm first and then flatten it. We can filter an entire CDM for a one or more specific person_ids with `subset`. 
 
 In case you're wondering if we copy the entire cdm when we create a subset you can be rest assured we do not. `cdm.subset(person_id = 0)` creates SQL views for each of the cdm tables with a `WHERE person_id = 0` clause applied to each table.

In [67]:
cdm = cdm.subset(person_id=[0])
cdm.flatten().execute()

     person_id  ...                                  type_concept_name
0            0  ...                   Outpatient detail - 1st position
1            0  ...                Carrier claim detail - 2nd position
2            0  ...                Carrier claim detail - 2nd position
3            0  ...                   Outpatient detail - 1st position
4            0  ...  Physician administered drug (identified as pro...
..         ...  ...                                                ...
271          0  ...                Carrier claim header - 1st position
272          0  ...                Carrier claim detail - 1st position
273          0  ...                Carrier claim header - 2nd position
274          0  ...                Carrier claim header - 3rd position
275          0  ...                Carrier claim detail - 2nd position

[276 rows x 10 columns]



You now have the total number of persons and a small preview. Use this pattern for any CDM table with `cdm["table_name"]` or `cdm.table_name`.

## Cleanup

Disconnect the CDM reference when done (releases resources).

In [68]:
cdm.disconnect()